name: Python mypy

on: [push, pull_request]

jobs:
  lint:
    name: Python mypy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup checkout
        uses: actions/checkout@v2
      - name: mypy
        run: |
          pip install mypy
          mypy dacapo --config-file ./mypy.ini
